{
 "title": "CrudApp",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage of CRUD App",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage of CRUD App",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total HTTP Requests by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (status) (http_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 8 },
   "targets": [
    { "expr": "rate(http_requests_total[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": " HTTP Response Size (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_response_size_bytes_sum[5m]) / rate(http_response_size_bytes_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95th Percentile Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Size (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_request_size_bytes_sum[5m]) / rate(http_request_size_bytes_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Response Time (5 min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}